stages:

- stage: BuildServices

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: BuildD0cker_SalesBookLB
    displayName: Build Docker Image for SalesBook.LB app

    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'conterinersregistrypc'
        repository: 'SalesBook.LB'
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.LB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
            tags: |
              $(Build.BuildId)
              latest

    - task: Docker@2
      inputs:
        containerRegistry: 'conterinersregistrypc'
        repository: 'SalesBook.WEB'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest