stages:

- stage: BuildServices

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: BuildD0cker_SalesBookLB
    displayName: Build Docker Image for SalesBook.LB app

    steps:

    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.LB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest